### ISSUE TITLE
bug(command): scheduler:consume --wait no longer works

### ISSUE THREAD

**Issue by jvancoillie** [Guikingone/SchedulerBundle#159]
Hi @Guikingone,

When I run the scheduler in `--wait` mode it gives me back control and no longer waits every minute
```bash 
developer@0461266b29f1:/var/www/app$ bin/console scheduler:consume --wait -vv

 ! [NOTE] The worker will wait for tasks every minutes

 // Quit the worker with CONTROL-C.

09:48:26 INFO      [app] The worker has been started ["failedTasks" => 0,"lastExecutedTask" => null]
09:48:26 INFO      [app] The worker has been stopped ["failedTasks" => 0,"lastExecutedTask" => null]
developer@0461266b29f1:/var/www/app$

**Comment by Guikingone** [comment]
Hi @jvancoillie 👋🏻 

Hum strange, do you have any scheduled tasks when launching the command?

**Comment by Guikingone** [comment]
Hi @jvancoillie 👋🏻 

I've pushed a first version of a fix via `dev-issue/159`, could you test it when you have a moment? Thanks 🙂

**Comment by Bastien2805** [comment]
Hi @Guikingone,

I think i have the same issue so i prefer ask directly here.

When i launch "scheduler:consume -w" i have this : 

```
$ bin/console scheduler:consume -w
                                                                                                                       
 [WARNING] Each tasks has already been executed for the current minute                                                  
                                                                                                                        
 Consider calling this command again at "2021-06-30 04:12"               
```                                     
                                                                                                                        
After, it just give me back control.

Thanks.

**Comment by Guikingone** [comment]
Hi @Bastien2805 👋🏻 

Yes, it could be related as I'm facing the issue locally, I'm currently in holidays so the PR has stale a little bit 😄 

I'm gonna fix it fast, could you test it against `dev-issue/159`?

**Comment by jvancoillie** [comment]
Hello @Guikingone 🥇 

I just tested the `dev/159` and it seems to work. 

thanks

**Comment by Bastien2805** [comment]
Hi @Guikingone,

I also tested it but it still doesn't work for me. Do you need more specific informations to resolve it ?

Thanks.

**Comment by Guikingone** [comment]
Hi @Bastien2805, 

Could you share the `scheduler.yaml` file? 

This way, we can see the transport used along with the tasks 🙂

**Comment by Bastien2805** [comment]
Hi, here is my scheduler.yaml file.

```
scheduler_bundle:
    transport:
        dsn: 'doctrine://default?execution_mode=first_in_first_out&table_name=scheduler_tasks'
```

**Comment by Guikingone** [comment]
Hi @Bastien2805 and @jvancoillie,

I've pushed a small fix (mainly in the worker), could you test it via `dev-issue/159`?

Thanks and very sorry for this bug 🙁

**Comment by Bastien2805** [comment]
Hi @Guikingone,

Thanks for the fix but it still doesn't work for me. Tell me if you need some information.

**Comment by Guikingone** [comment]
Hi @jvancoillie, 

Could you validate that if fix your issue when you have a moment? 

Thanks 🙂

**Comment by jvancoillie** [comment]
Hello @Guikingone, 

I just tested on `dev-issue / 159` with the following configuration :
```yaml
scheduler_bundle:
  transport:
    dsn: 'doctrine://default?execution_mode=first_in_first_out'
  tasks:
    foo:
      type: 'command'
      command: 'app:foo'
      description: 'simple task'
      single_run: true
```
the `wait` option seems to do its job and maybe a little too much because I no longer have the possibility to quit the worker` CTRL + C` :(
<img width="826" alt="Capture d’écran 2021-07-05 à 18 38 55" src="https://user-images.githubusercontent.com/21243943/124500563-48d04480-ddc0-11eb-84cc-74df87faef5a.png">

I also have behavior that IMHO shouldn't be. 
When I run the command `scheduler:consume --wait` a second time it displays the following warning 🤔 
<img width="826" alt="Capture d’écran 2021-07-05 à 18 44 12" src="https://user-images.githubusercontent.com/21243943/124500994-0a875500-ddc1-11eb-87cc-c398965cb2bb.png">

shouldn't it be able to resume sleeping mode WDYT ?

**Comment by Guikingone** [comment]
> the wait option seems to do its job and maybe a little too much because I no longer have the possibility to quit the worker CTRL + C

Hum, strange, I'm gonna explore this issue. 

> When I run the command scheduler:consume --wait a second time it displays the following warning

Yes, this behaviour has been introduced in `0.4.5` and discussed with @Bastien2805, https://github.com/Guikingone/SchedulerBundle/pull/161 should fix the issue, could you test it?

**Comment by jvancoillie** [comment]
> Yes, this behaviour has been introduced in `0.4.5` and discussed with @Bastien2805, #161 should fix the issue, could you test it?

👍 `dev-feat/wait_force` no longer display warning with `--force`option but it gives me back control, maybe this is normal because it should not contain the `dev-issue/159` fix, right?

**Comment by Guikingone** [comment]
> maybe this is normal because it should not contain the dev-issue/159 fix, right?

`dev-issue/159` is not implemented for now, that could be the reason, you're right 🙂

**Comment by Guikingone** [comment]
Hi @jvancoillie 👋🏻 

Could you confirm that `dev-issue/159` fix the "control" issue, I'm talking about the command ending process and not the `sleep` call, if so, could you open a new issue for the `sleep` call? 

Thanks 🙂

**Comment by Guikingone** [comment]
Hi @jvancoillie 👋🏻 

I've moved the `sleep` call issue to a new issue 🙂 

Link: https://github.com/Guikingone/SchedulerBundle/issues/165
