### ISSUE TITLE
Unable to find MessengerTaskRunner in Worker

### ISSUE THREAD

**Issue by Bastien2805** [Guikingone/SchedulerBundle#162]
Hi @Guikingone,

When i run `scheduler:consume -w` it can't launch my MessengerTask.

After some research and with add dump in Worker.php file i recover 6 TaskRunner (Shell, Command, Callback, Notification, Null and Chained) but not the MessengerTaskRunner and HttpTaskRunner.

You can reproduce it with : `dd(array_map(function ($runner){return get_class($runner);}, $this->getRunners()));` at line 80 in Worker.php file.

It returns : 
```
^ array:6 [
  0 => "SchedulerBundle\Runner\ShellTaskRunner"
  1 => "SchedulerBundle\Runner\CommandTaskRunner"
  2 => "SchedulerBundle\Runner\CallbackTaskRunner"
  3 => "SchedulerBundle\Runner\NotificationTaskRunner"
  4 => "SchedulerBundle\Runner\NullTaskRunner"
  5 => "SchedulerBundle\Runner\ChainedTaskRunner"
]
```

Is it normal ?

Thanks,

**Comment by Guikingone** [comment]
Hi @Bastien2805, 

Does the `Messenger` component is installed and does the `messenger.default_bus` service available? 🤔

**Comment by Bastien2805** [comment]
Hi @Guikingone :wave: ,

Yes both are OK and messenger is already used for other functionnality of the project and it works.

**Comment by Guikingone** [comment]
Hi @Bastien2805 

A fix has been pushed via `dev-issue/162`, could uou check if it fix the issue when you have a moment?

**Comment by Bastien2805** [comment]
Hi @Guikingone,

I tested it but it still doesn't work, I tried `dd()` again as I mentioned in my first comment and I get the same tasks.

**Comment by Guikingone** [comment]
Hi @Bastien2805, 

Strange situation, I've just pushed a new version of the fix, could you test it? It works locally but we never know 🙂

**Comment by Bastien2805** [comment]
Hi @Guikingone,

Everything seems to work, thank you very much! :smiley:

**Comment by Guikingone** [comment]
Hi, 

Fantastic news, it should be available via `0.5.4` 🙂
