### ISSUE TITLE
bug(worker): stop during task execution

### ISSUE THREAD

**Issue by Guikingone** [Guikingone/SchedulerBundle#185]
Created by @jvancoillie 

> Hello @Guikingone, 
> 
> Sorry for the late return it was vacation.
> 
> I just tested the quit worker via signal on version 0.6.2 which seems to contain this fix.
> 
> the `CTRL-C` displays the message "The task will be retried next time" but does not seem to completely stop the worker process and seems to move on to the next task. A new `CTRL-C` seems to have no direct effect but displays the same message after a while.
> 
> Wanting to check the status of the tasks, I cannot find the information that the task failed, would it be possible to display this information when calling the `scheduler:list` command
> 
> I attach a screenshot for ease of understanding.
> <img width="1350" alt="Capture d’écran 2021-09-07 à 19 05 01" src="https://user-images.githubusercontent.com/21243943/132383815-1d426889-0861-4f97-a765-874f5829ecb0.png">
> 
> _Originally posted by @jvancoillie in https://github.com/Guikingone/SchedulerBundle/issues/177#issuecomment-914475403_

**Comment by Guikingone** [comment]
Hi @jvancoillie 👋🏻 

Sorry for the delay, could you give me more informations? 

Maybe (if you can share it) the `scheduler.yaml` file? 

Thanks and sorry for the bug 🙂

**Comment by Guikingone** [comment]
I've pushed a fix via https://github.com/Guikingone/SchedulerBundle/pull/186, if you have a moment to test it 🙂 

It works locally but depending on the configuration, it may be a good idea to test it 😄

**Comment by jvancoillie** [comment]
Hello @Guikingone, 

Sorry for this late return, the return to work is complicated ... I'm a little overwhelmed :(

Just tested with the `dev-issue/185`and still have the same problem.

I have the following `scheduler.yaml` configuration : 

```yaml
scheduler_bundle:
  transport:
    dsn: 'doctrine://default?execution_mode=first_in_first_out'
  lock_store: 'lock.default.store'
  tasks:
    foo:
      type: 'command'
      command: 'app:foo'
      description: '2 mins placeholder task'
      single_run: true
    bar:
      type: 'command'
      command: 'app:bar'
      description: '1 mins placeholder task'
      single_run: true
```
<img width="1350" alt="Capture d’écran 2021-09-15 à 18 09 37" src="https://user-images.githubusercontent.com/21243943/133469703-01408593-398e-432e-80aa-d2e6a359460b.png">

**Comment by Guikingone** [comment]
Hi @jvancoillie 👋🏻 

No problem, hope the next weeks will be better for your 🙂 

I think I got how the bug occurs, if you have X tasks to execute then stop the worker when there's remaining tasks, it don't stop fully, I'm gonna investigate in this way 🙂

**Comment by Guikingone** [comment]
Well, I'm back 😄 

If you have a moment @jvancoillie, could you test the latest commit on `dev-issue/185`, it works locally but your feedback is more important 🙂

**Comment by jvancoillie** [comment]
With the last commit `0a08b07` it works fine, thanks.

If I can afford it, it would be interesting to have the status (for example `failed` or `canceled`) in the task list ;)
